name: Despliegue Automatico Tienda Texas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Subir cambios al Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Sincronizar archivos por SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: \${{ secrets.SFTP_USERNAME }}
          password: \${{ secrets.SFTP_PASSWORD }}
          port: 21098
          local-dir: ./
          server-dir: ./public_html/