name: Despliegue Automatico Tienda Texas

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Subir cambios al Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Sincronizar archivos por SFTP Puro
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 21098
          local_path: './*'
          remote_path: 'public_html'
          